'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { ChevronLeft,ChevronRight,Download,Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { secureFetch } from '@/lib/client-api'
type Cell={value:string;recordId:string;version:number};type Employee={cedula:string;nombre:string;sector:string;regional:string;gerencia:string;records:Record<string,Cell>};type Data={dates:string[];employees:Employee[];options:string[];total:number;page:number;pageSize:number};type Pair={regional:string;gerencia:string}
const noveltyClass=(value:string)=>{const v=value.toUpperCase();if(v==='VACANTE')return'bg-amber-100 text-amber-900';if(v.includes('ENFERMEDAD')||v.includes('ACCIDENTE')||v.includes('INASISTENCIA'))return'bg-red-100 text-red-900';if(v.includes('VACACIONES')||v.includes('LICENCIA'))return'bg-purple-100 text-purple-900';if(/^(COM|MKP|NEG|COO|C00)/.test(v)||v.startsWith('LABOR'))return'bg-emerald-50 text-emerald-900';return'bg-blue-50 text-blue-900'}
export default function ConsolidadoPage(){const [regionales,setRegionales]=useState<string[]>([]),[pairs,setPairs]=useState<Pair[]>([]),[regional,setRegional]=useState(''),[gerencia,setGerencia]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[exporting,setExporting]=useState(false)
useEffect(()=>{fetch('/api/initial').then(r=>r.json()).then(r=>{setRegionales(r.regionales??[]);setPairs(r.pares??[])})},[]);useEffect(()=>{const t=setTimeout(()=>{setSearch(q);setPage(1)},300);return()=>clearTimeout(t)},[q]);const gerencias=useMemo(()=>[...new Set(pairs.filter(p=>!regional||p.regional===regional).map(p=>p.gerencia))].sort(),[pairs,regional]);const params=useCallback((targetPage=page,size=50)=>new URLSearchParams({regional,gerencia,from,to,q:search,page:String(targetPage),pageSize:String(size)}).toString(),[regional,gerencia,from,to,search,page])
useEffect(()=>{if(!regional&&!gerencia)return;setLoading(true);fetch(`/api/consolidated?${params()}`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b}).then(setData).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[regional,gerencia,params])
async function update(cell:Cell,newValue:string){const reason=prompt('Motivo de la corrección (mínimo 5 caracteres):')?.trim();if(!reason||reason.length<5)return toast.error('El motivo es obligatorio.');const r=await secureFetch('/api/records/update',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({recordId:cell.recordId,version:cell.version,newValue,reason})});const body=await r.json();if(!r.ok)return toast.error(body.error);toast.success('Registro actualizado y auditado');setData(d=>d?({...d,employees:d.employees.map(e=>({...e,records:Object.fromEntries(Object.entries(e.records).map(([date,x])=>[date,x.recordId===cell.recordId?{...x,value:newValue,version:body.version}:x]))}))}):d)}
async function exportXlsx(){if(!data)return;setExporting(true);try{const all:Employee[]=[];const pages=Math.ceil(data.total/200);for(let p=1;p<=pages;p++){const r=await fetch(`/api/consolidated?${params(p,200)}`);if(!r.ok)throw new Error('No se pudo completar la exportación');all.push(...(await r.json()).employees)}const XLSX=await import('xlsx');const rows=all.map(e=>({Regional:e.regional,Gerencia:e.gerencia,Cédula:e.cedula,Nombre:e.nombre,Sector:e.sector,...Object.fromEntries(data.dates.map(d=>[d,e.records[d]?.value??'']))}));const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:14},{wch:28},{wch:16},{wch:32},{wch:16},...data.dates.map(()=>({wch:14}))];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Consolidado');XLSX.writeFile(wb,`consolidado_${from||'inicio'}_${to||'hoy'}.xlsx`)}catch(e){toast.error(e instanceof Error?e.message:'No se pudo exportar')}finally{setExporting(false)}}
const totalPages=Math.max(1,Math.ceil((data?.total??0)/(data?.pageSize??50)));return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black">Consolidado</h1><p className="text-sm text-slate-500">Matriz paginada con correcciones auditadas.</p></div><button className="btn-secondary" disabled={!data||exporting} onClick={exportXlsx}>{exporting?<Loader2 className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}Exportar XLSX</button></div>
<div className="card grid gap-3 p-4 md:grid-cols-3 lg:grid-cols-5"><label className="label">Regional<select className="field mt-1" value={regional} onChange={e=>{setRegional(e.target.value);setGerencia('');setPage(1)}}><option value="">Todas</option>{regionales.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">Gerencia<select className="field mt-1" value={gerencia} onChange={e=>{setGerencia(e.target.value);setPage(1)}}><option value="">Todas</option>{gerencias.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">Desde<input className="field mt-1" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label className="label">Hasta<input className="field mt-1" type="date" value={to} min={from} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label><label className="label">Buscar<input className="field mt-1" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nombre, cédula o sector"/></label></div>
{loading&&<div className="grid place-items-center py-12"><Loader2 className="h-7 w-7 animate-spin"/></div>}{data&&!loading&&<><div className="card max-h-[68vh] overflow-auto"><table className="min-w-full border-separate border-spacing-0 text-sm"><thead><tr><th className="sticky left-0 top-0 z-30 min-w-64 bg-slate-100 p-3 text-left">Colaborador</th><th className="sticky top-0 z-20 min-w-36 bg-slate-100 p-3">Sector</th>{data.dates.map(d=><th className="sticky top-0 z-20 whitespace-nowrap bg-slate-100 p-3" key={d}>{d}</th>)}</tr></thead><tbody>{data.employees.map(e=><tr key={`${e.cedula}:${e.sector}`}><td className="sticky left-0 z-10 border-t bg-white p-3"><b>{e.nombre}</b><p className="text-xs text-slate-400">{e.cedula}</p></td><td className="border-t p-3">{e.sector}</td>{data.dates.map(d=><td className="border-t p-2" key={d}>{e.records[d]?<select aria-label={`${e.nombre} ${d}`} className={`field min-w-44 text-xs ${noveltyClass(e.records[d].value)}`} value={e.records[d].value} onChange={x=>update(e.records[d],x.target.value)}>{[...new Set([e.records[d].value,...data.options])].map(o=><option key={o}>{o}</option>)}</select>:<span className="text-slate-300">—</span>}</td>)}</tr>)}</tbody></table></div><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{data.total.toLocaleString()} colaboradores · Página {page} de {totalPages}</p><div className="flex gap-2"><button className="btn-secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft className="h-4 w-4"/>Anterior</button><button className="btn-secondary" disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)}>Siguiente<ChevronRight className="h-4 w-4"/></button></div></div></>}</div>}
