'use client'
import {useEffect,useMemo,useState} from 'react'
import {Download,Loader2,Search} from 'lucide-react'
import {toast} from 'sonner'
import type {StructureRow} from '@/lib/types'

export default function EstructuraPage(){
 const [rows,setRows]=useState<StructureRow[]>([]),[q,setQ]=useState(''),[regional,setRegional]=useState(''),[gerencia,setGerencia]=useState(''),[estado,setEstado]=useState(''),[loading,setLoading]=useState(true),[exporting,setExporting]=useState(false)
 useEffect(()=>{fetch('/api/structure').then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b}).then(r=>setRows(r.rows??[])).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[])
 const regionales=useMemo(()=>[...new Set(rows.map(r=>r.regional).filter(Boolean))].sort(),[rows]),gerencias=useMemo(()=>[...new Set(rows.filter(r=>!regional||r.regional===regional).map(r=>r.gerencia).filter(Boolean))].sort(),[rows,regional])
 const filtered=useMemo(()=>{const needle=q.toLowerCase();return rows.filter(r=>(!needle||`${r.nombre} ${r.cedula} ${r.sector}`.toLowerCase().includes(needle))&&(!regional||r.regional===regional)&&(!gerencia||r.gerencia===gerencia)&&(!estado||r.estado===estado))},[rows,q,regional,gerencia,estado])
 const hired=filtered.filter(r=>r.estado==='CONTRATADO').length,vacancies=filtered.filter(r=>r.estado==='VACANTE'||r.nombre==='VACANTE').length,headcount=filtered.length?Math.round(hired/filtered.length*100):0
 function clear(){setQ('');setRegional('');setGerencia('');setEstado('')}
 async function exportExcel(){setExporting(true);try{const XLSX=await import('xlsx'),data=filtered.map(r=>({Regional:r.regional,Gerencia:r.gerencia,Sector:r.sector,Cargo:r.cargo,Cédula:r.cedula,Colaborador:r.nombre,'Número Personal':r.numeroPersonal,'Correo Personal':r.correo,Ingreso:r.fechaIngreso,Estado:r.estado})),sheet=XLSX.utils.json_to_sheet(data),book=XLSX.utils.book_new();sheet['!cols']=[14,28,18,30,16,34,18,32,14,14].map(wch=>({wch}));XLSX.utils.book_append_sheet(book,sheet,'Estructura');XLSX.writeFile(book,'Estructura_Serdan.xlsx')}catch{toast.error('No se pudo exportar el archivo')}finally{setExporting(false)}}
 return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black">Estructura nacional</h1><p className="text-sm text-slate-500">Consulta de posiciones y colaboradores.</p></div><button className="btn-secondary" disabled={exporting||!filtered.length} onClick={exportExcel}>{exporting?<Loader2 className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}Exportar Excel</button></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Cargos aprobados" value={filtered.length} color="text-indigo-700"/><Stat label="Contratados" value={hired} color="text-emerald-700"/><Stat label="Vacantes" value={vacancies} color="text-red-700"/><Stat label="Headcount" value={`${headcount}%`} color="text-slate-800"/></div>
 <section className="card grid gap-3 p-4 md:grid-cols-5"><label className="label">Buscar<div className="relative mt-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input className="field pl-9" placeholder="Nombre, cédula o sector" value={q} onChange={e=>setQ(e.target.value)}/></div></label><label className="label">Regional<select className="field mt-1" value={regional} onChange={e=>{setRegional(e.target.value);setGerencia('')}}><option value="">Todas</option>{regionales.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">Gerencia<select className="field mt-1" value={gerencia} onChange={e=>setGerencia(e.target.value)}><option value="">Todas</option>{gerencias.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">Estado<select className="field mt-1" value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos</option><option>CONTRATADO</option><option>VACANTE</option></select></label><button className="btn-secondary self-end" onClick={clear}>Limpiar</button></section>
 {loading?<div className="grid place-items-center py-16"><Loader2 className="h-7 w-7 animate-spin"/></div>:<div className="card max-h-[65vh] overflow-auto"><table className="min-w-full text-sm"><thead className="sticky top-0 z-10 bg-slate-100"><tr>{['Regional','Gerencia','Sector','Cargo','Cédula','Colaborador','Número Personal','Correo Personal','Ingreso','Estado'].map(h=><th className="whitespace-nowrap p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map((r,i)=><tr className="border-t border-slate-100" key={`${r.sector}:${r.cedula}:${i}`}><td className="p-3">{r.regional}</td><td className="p-3">{r.gerencia}</td><td className="p-3 font-bold text-blue-700">{r.sector}</td><td className="p-3">{r.cargo}</td><td className="p-3">{r.cedula}</td><td className="p-3 font-semibold">{r.nombre}</td><td className="p-3">{r.numeroPersonal}</td><td className="p-3">{r.correo}</td><td className="p-3">{r.fechaIngreso}</td><td className={`p-3 font-bold ${r.estado==='VACANTE'?'text-red-700':r.estado==='CONTRATADO'?'text-emerald-700':''}`}>{r.estado}</td></tr>)}</tbody></table>{!filtered.length&&<p className="p-8 text-center text-slate-500">No hay resultados para los filtros seleccionados.</p>}</div>}</div>
}
function Stat({label,value,color}:{label:string;value:string|number;color:string}){return <div className="card p-4 text-center"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className={`text-3xl font-black ${color}`}>{value}</p></div>}
