'use client'
import {useEffect,useMemo,useState} from 'react'
import {CheckCircle2,Loader2,Search,Send,RotateCcw} from 'lucide-react'
import {toast} from 'sonner'
import type {Assignment} from '@/lib/types'
import {resilientFetch,secureFetch} from '@/lib/client-api'

type Payload={groups:Record<string,Assignment[]>;availablePositions:string[];options:string[];stats:{expected:number;registered:number;covered:number};completed:boolean}
type Draft={requestId:string;values:Record<string,string>}
const draftKey=(gerencia:string)=>`ausentismo:draft:${gerencia}`

export function Registration(){
 const [gerencias,setGerencias]=useState<string[]>([]),[gerencia,setGerencia]=useState(''),[data,setData]=useState<Payload|null>(null),[values,setValues]=useState<Record<string,string>>({}),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[requestId,setRequestId]=useState('')
 useEffect(()=>{resilientFetch('/api/initial').then(async r=>{if(!r.ok)throw new Error((await r.json()).error);return r.json()}).then(r=>setGerencias(r.gerencias??[])).catch(e=>setError(e instanceof Error?e.message:'Sin conexión'))},[])
 useEffect(()=>{if(!gerencia){setData(null);return}const controller=new AbortController();setLoading(true);setError('');resilientFetch(`/api/assignments?gerencia=${encodeURIComponent(gerencia)}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);return r.json() as Promise<Payload>}).then(r=>{if(controller.signal.aborted)return;setData(r);const seed:Record<string,string>=Object.fromEntries(Object.values(r.groups??{}).flat().map(x=>[x.id,x.valorReportado]));const saved=localStorage.getItem(draftKey(gerencia));const draft:Draft|undefined=saved?JSON.parse(saved):undefined;setValues({...seed,...draft?.values});setRequestId(draft?.requestId??crypto.randomUUID())}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Sin conexión')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[gerencia])
 useEffect(()=>{if(gerencia&&requestId)localStorage.setItem(draftKey(gerencia),JSON.stringify({requestId,values}))},[gerencia,requestId,values])
 const employees=useMemo(()=>Object.values(data?.groups??{}).flat(),[data]),missing=employees.filter(e=>!e.autoVacante&&!values[e.id]),progress=employees.length?Math.round((employees.length-missing.length)/employees.length*100):0
 const groups=useMemo(()=>Object.fromEntries(Object.entries(data?.groups??{}).map(([name,rows])=>[name,rows.filter(r=>`${r.nombre} ${r.cedula} ${r.sector}`.toLowerCase().includes(query.toLowerCase()))]).filter(([,rows])=>(rows as Assignment[]).length)),[data,query]) as Record<string,Assignment[]>
 const occupied=new Set(employees.map(e=>values[e.id]).filter(v=>data?.availablePositions.includes(v)))
 function resetDraft(){if(!confirm('¿Descartar el borrador de esta gerencia?'))return;localStorage.removeItem(draftKey(gerencia));setRequestId(crypto.randomUUID());setValues(Object.fromEntries(employees.map(x=>[x.id,x.valorReportado])))}
 async function save(){if(missing.length)return toast.error(`Faltan ${missing.length} registros`);const uncovered=data?.availablePositions.filter(p=>!occupied.has(p))??[],warning=uncovered.length?`\n\nSectores sin cobertura: ${uncovered.join(', ')}`:'';if(!confirm(`¿Confirmas el envío de ${employees.length} registros? Esta acción será auditada.${warning}`))return;const records=employees.map(({id,esSuper,autoVacante,...row})=>({...row,valorReportado:values[id]}));setSaving(true);try{const res=await secureFetch('/api/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId,records}),timeoutMs:20_000});const body=await res.json();if(!res.ok)throw new Error(body.error);localStorage.removeItem(draftKey(gerencia));toast.success(body.replayed?'El lote ya había sido guardado; no se duplicó.':`${body.count} registros guardados`);setGerencia('');setData(null)}catch(e){toast.error(navigator.onLine?(e instanceof Error?e.message:'No se pudo guardar'):'Sin conexión. El borrador quedó guardado; reintenta cuando vuelva la señal.')}finally{setSaving(false)}}
 return <div className="space-y-5"><div><h1 className="text-2xl font-black">Registro diario</h1><p className="text-sm text-slate-500">Gestión de talento operativo con guardado idempotente.</p></div>
 <section className="card p-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="label">Gerencia<select className="field mt-1" value={gerencia} onChange={e=>setGerencia(e.target.value)}><option value="">Seleccione una gerencia</option>{gerencias.map(g=><option key={g}>{g}</option>)}</select></label><label className="label">Buscar<div className="relative mt-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input className="field pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, cédula o sector"/></div></label>{data&&<div className="flex items-end gap-2"><div className="rounded-lg bg-blue-50 px-4 py-2 text-center"><p className="text-xs font-bold text-blue-700">Progreso</p><p className="text-xl font-black text-blue-900">{progress}%</p></div><button className="rounded-lg p-3 hover:bg-slate-100" onClick={resetDraft} aria-label="Descartar borrador"><RotateCcw className="h-5 w-5"/></button></div>}</div>{data&&<><div className="mt-3 grid max-w-sm grid-cols-2 gap-3"><div className="rounded-lg bg-emerald-50 p-3 text-center"><p className="text-xs font-bold uppercase text-emerald-700">Cumplimiento</p><p className="text-xl font-black text-emerald-900">{data.stats.expected?Math.round(data.stats.covered/data.stats.expected*100):0}%</p></div><div className="rounded-lg bg-indigo-50 p-3 text-center"><p className="text-xs font-bold uppercase text-indigo-700">Registros</p><p className="text-xl font-black text-indigo-900">{data.stats.registered}</p></div></div><div className="mt-3 h-2 overflow-hidden rounded bg-slate-100" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><div className="h-full bg-blue-700 transition-all" style={{width:`${progress}%`}}/></div></>}</section>
 {loading&&<div className="grid place-items-center py-16" role="status"><Loader2 className="h-8 w-8 animate-spin text-blue-700"/><span className="sr-only">Cargando operación</span></div>}{error&&<div className="card border-red-200 p-5 text-red-700" role="alert">{error}</div>}{data?.completed&&<div className="card flex items-center gap-3 p-6 text-emerald-700"><CheckCircle2/><b>La gerencia ya quedó completada para hoy.</b></div>}
 {!loading&&data&&!employees.length&&!data.completed&&<div className="card p-8 text-center text-slate-500">No hay posiciones pendientes para esta gerencia.</div>}
 {Object.entries(groups).map(([group,rows])=><section className="card overflow-hidden" key={group}><h2 className="border-b bg-slate-50 px-4 py-3 text-sm font-black uppercase">{group} · {rows.length}</h2><div className="divide-y">{rows.map(e=><div key={e.id} className="grid gap-3 p-4 md:grid-cols-[1fr_280px] md:items-center"><div><p className="font-bold">{e.nombre}</p><p className="text-xs text-slate-500">{e.cargo} · ID {e.cedula}</p><p className="mt-1 text-sm font-bold text-blue-700">{e.sector}</p></div><label><span className="sr-only">Asignación para {e.nombre}</span><select className="field" disabled={e.autoVacante} value={values[e.id]??''} onChange={x=>setValues(v=>({...v,[e.id]:x.target.value}))}><option value="">Asignar…</option>{!e.esSuper&&<option value={e.sector}>{e.sector}</option>}{e.esSuper&&data?.availablePositions.map(p=><option key={p} value={p} disabled={occupied.has(p)&&values[e.id]!==p}>{p}</option>)}{data?.options.filter(n=>!(e.esSuper&&n==='Vacante')&&n!==e.sector).map(n=><option key={n}>{n}</option>)}</select></label></div>)}</div></section>)}
 {data&&employees.length>0&&<div className="sticky bottom-4 flex justify-end"><button className="btn-primary shadow-lg" disabled={saving||missing.length>0} onClick={save}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}Confirmar y guardar ({employees.length})</button></div>}</div>
}
