import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import XLSX from 'xlsx'

export const STRUCTURE_ALIASES={regional:['REGIONAL'],gerencia:['GERENCIA'],sector:['SECTOR /POSICION','SECTOR/POSICION','SECTOR','POSICION'],estado:['ESTADO'],cedula:['CEDULA','DOCUMENTO'],nombre:['NOMBRE','NOMBRE COMPLETO'],cargo:['CARGO APROBADO','CARGO'],cargoAvancys:['CARGO AVANCYS'],tipo:['TIPO'],fechaIngreso:['FECHA INGRESO','FECHA_INGRESO'],unidad:['UNIDAD','UNIDAD DE NEGOCIO'],numeroPersonal:['NUMERO PERSONAL','NUMERO_PERSONAL'],correo:['CORREO PERSONAL','CORREO']}
export const RECORD_ALIASES={regional:['REGIONAL'],gerencia:['GERENCIA'],cedula:['CEDULA','DOCUMENTO'],nombre:['NOMBRE','NOMBRE COMPLETO'],cargo:['CARGO'],sector:['SECTOR','SECTOR /POSICION','SECTOR/POSICION','POSICION'],fechaIngreso:['FECHA_INGRESO','FECHA INGRESO'],fechaRegistro:['FECHA_REGISTRO','FECHA REGISTRO','VALE','FECHA'],valorReportado:['VALOR_REPORTADO','VALOR REPORTADO','INASISTENCIA','NOVEDAD']}

export const normalizeText=value=>String(value??'').replace(/\u00a0/g,' ').replace(/[\u2007\u202f]/g,' ').normalize('NFC').replace(/\s+/g,' ').trim()
export const normalizeHeader=value=>normalizeText(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').toUpperCase()
export const normalizeId=value=>{if(typeof value==='number'&&Number.isFinite(value))return String(Math.trunc(value));const raw=normalizeText(value);return /^\d+\.0$/.test(raw)?raw.slice(0,-2):raw}
export function isoDateBogota(value){
 if(value instanceof Date&&!Number.isNaN(value.valueOf()))return `${value.getUTCFullYear()}-${String(value.getUTCMonth()+1).padStart(2,'0')}-${String(value.getUTCDate()).padStart(2,'0')}`
 if(typeof value==='number'&&Number.isFinite(value)){const d=new Date(Date.UTC(1899,11,30)+Math.trunc(value)*86400000);return isoDateBogota(d)}
 const raw=normalizeText(value);if(!raw||raw==='-')return ''
 let m=raw.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return validDate(`${m[1]}-${m[2]}-${m[3]}`)
 m=raw.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(m)return validDate(`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`)
 return ''
}
function validDate(value){const d=new Date(`${value}T12:00:00-05:00`);return Number.isNaN(d.valueOf())||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)!==value?'':value}
export const stableKey=(...parts)=>parts.map(x=>normalizeText(x).toUpperCase()).join('|')
export const isCollaboratorManagement=value=>/(?:ELITE|SHARE|HSE)|^RE\s/i.test(normalizeText(value))
const recordIdentity=row=>/^(VACANTE|VACANTE-)/i.test(row.cedula)||normalizeHeader(row.nombre)==='VACANTE'?`VACANTE:${row.sector}`:row.cedula||row.nombre
export const sha256=value=>crypto.createHash('sha256').update(value).digest('hex')
export function stableUuid(seed){const hex=sha256(seed).slice(0,32).split('');hex[12]='4';hex[16]=((parseInt(hex[16],16)&3)|8).toString(16);return `${hex.slice(0,8).join('')}-${hex.slice(8,12).join('')}-${hex.slice(12,16).join('')}-${hex.slice(16,20).join('')}-${hex.slice(20).join('')}`}

function workbookRows(file,sheetName){const bytes=fs.readFileSync(file),workbook=XLSX.read(bytes,{type:'buffer',cellDates:true,cellNF:false,cellText:false});const actual=workbook.SheetNames.find(x=>normalizeHeader(x)===normalizeHeader(sheetName))??workbook.SheetNames[0];if(!actual)throw new Error(`Sin hojas: ${file}`);return{rows:XLSX.utils.sheet_to_json(workbook.Sheets[actual],{header:1,defval:null,raw:true}),sheet:actual,hash:sha256(bytes)}}
function findHeader(rows,aliases){let best={index:-1,score:-1};rows.slice(0,30).forEach((row,index)=>{const heads=new Set(row.map(normalizeHeader));const score=Object.values(aliases).filter(names=>names.some(x=>heads.has(normalizeHeader(x)))).length;if(score>best.score)best={index,score}});if(best.score<3)throw new Error('No se pudo detectar una fila de encabezados confiable');return best.index}
function columns(headers,aliases){const normalized=headers.map(normalizeHeader);return Object.fromEntries(Object.entries(aliases).map(([key,names])=>[key,normalized.findIndex(x=>names.map(normalizeHeader).includes(x))]))}
const value=(row,index)=>index>=0?row[index]:null
const blank=row=>row.every(x=>normalizeText(x)==='')

export function mapRecordMatrix(rows){const headerIndex=findHeader(rows,RECORD_ALIASES),cols=columns(rows[headerIndex],RECORD_ALIASES);return rows.slice(headerIndex+1).map((row,i)=>{if(blank(row))return null;return{sourceRow:headerIndex+i+2,regional:normalizeText(value(row,cols.regional)),gerencia:normalizeText(value(row,cols.gerencia)),cedula:normalizeId(value(row,cols.cedula)),nombre:normalizeText(value(row,cols.nombre))||'VACANTE',cargo:normalizeText(value(row,cols.cargo)),sector:normalizeText(value(row,cols.sector)),fechaIngreso:isoDateBogota(value(row,cols.fechaIngreso))||'-',fechaRegistro:isoDateBogota(value(row,cols.fechaRegistro)),valorReportado:normalizeText(value(row,cols.valorReportado))}}).filter(Boolean).filter(r=>r.gerencia||r.sector||r.fechaRegistro)}

function classify(rows,keyOf,fingerprintOf){const groups=new Map();for(const row of rows){const key=keyOf(row);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}const valid=[],duplicates=[],conflicts=[];for(const [key,items] of groups){const fingerprints=new Set(items.map(fingerprintOf));if(fingerprints.size>1){for(const row of items)conflicts.push({...row,issue:'Misma clave con contenidos diferentes',key});continue}valid.push(items[0]);for(const row of items.slice(1))duplicates.push({...row,issue:'Duplicado exacto',key,duplicateOf:items[0].sourceRow})}return{valid,duplicates,conflicts}}

export function auditStructure(file){const source=workbookRows(file,'Estructura Nacional'),headerIndex=findHeader(source.rows,STRUCTURE_ALIASES),cols=columns(source.rows[headerIndex],STRUCTURE_ALIASES),candidates=[],rejected=[];source.rows.slice(headerIndex+1).forEach((row,i)=>{if(blank(row))return;const sourceRow=headerIndex+i+2,record={sourceRow,regional:normalizeText(value(row,cols.regional)),gerencia:normalizeText(value(row,cols.gerencia)),sector:normalizeText(value(row,cols.sector)),estado:normalizeText(value(row,cols.estado)).toUpperCase(),cedula:normalizeId(value(row,cols.cedula)),nombre:normalizeText(value(row,cols.nombre))||'VACANTE',cargo:normalizeText(value(row,cols.cargo)),cargoAvancys:normalizeText(value(row,cols.cargoAvancys)),tipo:normalizeText(value(row,cols.tipo)),fechaIngreso:isoDateBogota(value(row,cols.fechaIngreso)),unidad:normalizeText(value(row,cols.unidad)),numeroPersonal:normalizeId(value(row,cols.numeroPersonal)),correo:normalizeText(value(row,cols.correo)).toLowerCase()};if(!record.regional&&!record.gerencia&&!record.sector)return;const missing=['regional','gerencia','sector'].filter(k=>!record[k]);if(missing.length)rejected.push({...record,issue:`Campos obligatorios vacíos: ${missing.join(', ')}`});else candidates.push(record)});const result=classify(candidates,r=>isCollaboratorManagement(r.gerencia)?stableKey(r.gerencia,'PERSONA',r.cedula||r.numeroPersonal||r.sector):stableKey(r.gerencia,r.sector),r=>sha256(JSON.stringify(r,Object.keys(r).filter(k=>k!=='sourceRow').sort())));return{source:{file:path.resolve(file),sheet:source.sheet,sha256:source.hash,headerRow:headerIndex+1},...result,rejected}}

export function auditRecords(file,structure){const source=workbookRows(file,'Consolidado'),headerIndex=findHeader(source.rows,RECORD_ALIASES),cols=columns(source.rows[headerIndex],RECORD_ALIASES),candidates=[],rejected=[];source.rows.slice(headerIndex+1).forEach((row,i)=>{if(blank(row))return;const sourceRow=headerIndex+i+2,rawDate=value(row,cols.fechaRegistro),record={sourceRow,regional:normalizeText(value(row,cols.regional)),gerencia:normalizeText(value(row,cols.gerencia)),cedula:normalizeId(value(row,cols.cedula)),nombre:normalizeText(value(row,cols.nombre))||'VACANTE',cargo:normalizeText(value(row,cols.cargo)),sector:normalizeText(value(row,cols.sector)),fechaIngreso:isoDateBogota(value(row,cols.fechaIngreso))||'-',fechaRegistro:isoDateBogota(rawDate),valorReportado:normalizeText(value(row,cols.valorReportado))};const missing=['gerencia','sector','fechaRegistro','valorReportado'].filter(k=>!record[k]);if(!record.fechaRegistro&&normalizeText(rawDate))missing.push('fechaRegistro inválida');if(missing.length)rejected.push({...record,issue:`Campos obligatorios vacíos o inválidos: ${[...new Set(missing)].join(', ')}`});else candidates.push(record)});const result=classify(candidates,r=>isCollaboratorManagement(r.gerencia)?stableKey(r.fechaRegistro,r.gerencia,'PERSONA',recordIdentity(r)):stableKey(r.fechaRegistro,r.gerencia,r.sector),r=>sha256(JSON.stringify(r,Object.keys(r).filter(k=>k!=='sourceRow').sort())));const structureKeys=new Set(structure.valid.map(r=>stableKey(r.gerencia,r.sector))),warnings=result.valid.filter(r=>!structureKeys.has(stableKey(r.gerencia,r.sector))).map(r=>({...r,issue:'Posición histórica no encontrada en la estructura actual',key:stableKey(r.fechaRegistro,r.gerencia,r.sector)}));return{source:{file:path.resolve(file),sheet:source.sheet,sha256:source.hash,headerRow:headerIndex+1},valid:result.valid,duplicates:result.duplicates,conflicts:result.conflicts,rejected,warnings}}

export function buildAudit(structureFile,recordsFile){const structure=auditStructure(structureFile),records=auditRecords(recordsFile,structure),summary={generatedAt:new Date().toISOString(),timeZone:'America/Bogota',readOnly:true,structure:Object.fromEntries(['valid','duplicates','conflicts','rejected'].map(k=>[k,structure[k].length])),records:Object.fromEntries(['valid','duplicates','conflicts','rejected','warnings'].map(k=>[k,records[k].length]))};const confirmation=`IMPORT:${sha256(`${structure.source.sha256}:${records.source.sha256}:${records.valid.length}`).slice(0,12)}`;return{summary,confirmation,structure,records}}

export function writeAudit(audit,outputDir){fs.mkdirSync(outputDir,{recursive:true});fs.writeFileSync(path.join(outputDir,'summary.json'),JSON.stringify({summary:audit.summary,confirmation:audit.confirmation,sources:{structure:audit.structure.source,records:audit.records.source}},null,2));for(const source of ['structure','records'])for(const category of ['valid','duplicates','conflicts','rejected',...(source==='records'?['warnings']:[])])fs.writeFileSync(path.join(outputDir,`${source}-${category}.jsonl`),audit[source][category].map(x=>JSON.stringify(x)).join('\n')+(audit[source][category].length?'\n':''));return path.resolve(outputDir)}
