import fs from 'node:fs'
import path from 'node:path'
import {google} from 'googleapis'
import {mapRecordMatrix,normalizeText,stableKey} from './import-utils.mjs'

function loadEnv(file='.env'){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);if(!m||process.env[m[1]])continue;let v=m[2].trim();if(v.startsWith('"')&&v.endsWith('"'))v=v.slice(1,-1);process.env[m[1]]=v.replace(/\\n/g,'\n')}}loadEnv()
const args=Object.fromEntries(process.argv.slice(2).map(x=>{const[k,...v]=x.replace(/^--/,'').split('=');return[k,v.join('=')]})),required=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','GOOGLE_SERVICE_ACCOUNT_EMAIL','GOOGLE_PRIVATE_KEY','GOOGLE_RECORDS_SPREADSHEET_ID'];for(const name of required)if(!process.env[name])throw new Error(`Falta ${name}`)
const base=process.env.SUPABASE_URL.replace(/\/$/,''),token=process.env.SUPABASE_SERVICE_ROLE_KEY,db=[];for(let offset=0;;offset+=1000){const response=await fetch(`${base}/rest/v1/daily_records?select=id,operational_date,regional,gerencia,cedula,nombre,cargo,source_position,fecha_ingreso,reported_value&order=operational_date,gerencia,source_position&limit=1000&offset=${offset}`,{headers:{apikey:token,authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(`Supabase ${response.status}`);const page=await response.json();db.push(...page);if(page.length<1000)break}
const auth=new google.auth.JWT({email:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key:process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g,'\n'),scopes:['https://www.googleapis.com/auth/spreadsheets.readonly']}),sheets=google.sheets({version:'v4',auth}),tab=process.env.GOOGLE_CONSOLIDATED_SHEET??'Consolidado',response=await sheets.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_RECORDS_SPREADSHEET_ID,range:`'${tab}'!A:Z`,valueRenderOption:'UNFORMATTED_VALUE',dateTimeRenderOption:'FORMATTED_STRING'}),sheet=mapRecordMatrix(response.data.values??[])
const canonical=r=>JSON.stringify({cedula:normalizeText(r.cedula),nombre:normalizeText(r.nombre),cargo:normalizeText(r.cargo),fechaIngreso:normalizeText(r.fechaIngreso||'-'),valorReportado:normalizeText(r.valorReportado)}),keyOf=r=>stableKey(r.fechaRegistro,r.gerencia,r.sector),group=rows=>{const map=new Map();for(const row of rows){const key=keyOf(row);if(!map.has(key))map.set(key,[]);map.get(key).push(row)}return map},dbRows=db.map(r=>({id:r.id,fechaRegistro:r.operational_date,regional:r.regional,gerencia:r.gerencia,cedula:r.cedula,nombre:r.nombre,cargo:r.cargo,sector:r.source_position,fechaIngreso:r.fecha_ingreso??'-',valorReportado:r.reported_value})),dbMap=group(dbRows),sheetMap=group(sheet),keys=new Set([...dbMap.keys(),...sheetMap.keys()]),missingInSheets=[],extraInSheets=[],mismatched=[],duplicates=[]
for(const key of keys){const left=dbMap.get(key)??[],right=sheetMap.get(key)??[];if(left.length>1||right.length>1)duplicates.push({key,postgres:left.length,sheets:right.length});if(!right.length){missingInSheets.push({key,count:left.length});continue}if(!left.length){extraInSheets.push({key,count:right.length});continue}const a=left.map(canonical).sort(),b=right.map(canonical).sort();if(JSON.stringify(a)!==JSON.stringify(b))mismatched.push({key,postgresCount:left.length,sheetsCount:right.length,postgresValues:a,sheetValues:b})}
const report={dryRun:true,generatedAt:new Date().toISOString(),key:'fechaRegistro|gerencia|sector',postgres:dbRows.length,sheets:sheet.length,missingInSheets,extraInSheets,mismatched,duplicates,totals:{missingInSheets:missingInSheets.length,extraInSheets:extraInSheets.length,mismatched:mismatched.length,duplicateKeys:duplicates.length}},output=args.output??path.join('reports','reconciliation',new Date().toISOString().replace(/[:.]/g,'-')+'.json');fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,missingInSheets:missingInSheets.slice(0,20),extraInSheets:extraInSheets.slice(0,20),mismatched:mismatched.slice(0,20),duplicates:duplicates.slice(0,20),report:path.resolve(output)},null,2));if(missingInSheets.length||extraInSheets.length||mismatched.length)process.exitCode=2
