'use client'
import { useEffect,useMemo,useState } from 'react'
import { Download,Info,Loader2 } from 'lucide-react'
import { toast } from 'sonner'
type Pair={regional:string;gerencia:string};type Group={name:string;expected:number;registered:number;compliance:number};type EventRow={regional:string;gerencia:string;cedula:string;nombre:string;date?:string};type Report={latest:string;kpis:{expected:number;registered:number;compliance:number;absences:number;vacancies:number;uncovered:number;birthdays:number;entries:number;exits:number};byRegional:Group[];byManagement:Group[];byNovelty:[string,number][];daily:{date:string;records:number;absences:number;vacancies:number}[];monthly:{month:string;records:number;absences:number;vacancies:number}[];uncovered:{regional:string;gerencia:string;sector:string;nombre:string}[];details:{birthdays:EventRow[];entries:(EventRow&{fechaIngreso?:string})[];exits:EventRow[]};definitions:Record<string,string>}
const today=new Date().toISOString().slice(0,10),monthAgo=new Date(Date.now()-29*86_400_000).toISOString().slice(0,10)
const Bar=({value,max,label,color='bg-blue-700'}:{value:number;max:number;label:string;color?:string})=><div className="h-3 rounded bg-slate-100" role="img" aria-label={`${label}: ${value}`}><div className={`h-3 rounded ${color}`} style={{width:`${max?Math.max(2,value/max*100):0}%`}}/></div>
export default function DashboardPage(){const [pairs,setPairs]=useState<Pair[]>([]),[regionales,setRegionales]=useState<string[]>([]),[regional,setRegional]=useState(''),[gerencia,setGerencia]=useState(''),[from,setFrom]=useState(monthAgo),[to,setTo]=useState(today),[d,setD]=useState<Report|null>(null),[loading,setLoading]=useState(false),[exporting,setExporting]=useState(false);useEffect(()=>{fetch('/api/initial').then(r=>r.json()).then(r=>{setPairs(r.pares??[]);setRegionales(r.regionales??[])})},[]);const gerencias=useMemo(()=>[...new Set(pairs.filter(p=>!regional||p.regional===regional).map(p=>p.gerencia))].sort(),[pairs,regional]);useEffect(()=>{setLoading(true);const s=new URLSearchParams({regional,gerencia,from,to});fetch(`/api/dashboard?${s}`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b}).then(setD).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[regional,gerencia,from,to])
async function exportXlsx(){if(!d)return;setExporting(true);try{const XLSX=await import('xlsx'),wb=XLSX.utils.book_new(),add=(name:string,rows:unknown[])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),name);add('KPIs',Object.entries(d.kpis).map(([Indicador,Valor])=>({Indicador,Valor})));add('Fórmulas',Object.entries(d.definitions).map(([Indicador,Fórmula])=>({Indicador,Fórmula})));add('Cumplimiento',d.byManagement);add('Tendencia diaria',d.daily);add('Tendencia mensual',d.monthly);add('Novedades',d.byNovelty.map(([Novedad,Total])=>({Novedad,Total})));add('Sin cobertura',d.uncovered);add('Cumpleaños',d.details.birthdays);add('Ingresos',d.details.entries);add('Retiros',d.details.exits);XLSX.writeFile(wb,`dashboard_${from||'inicio'}_${to||'hoy'}.xlsx`)}finally{setExporting(false)}}
if(!d&&loading)return <p className="flex items-center gap-2"><Loader2 className="h-5 w-5 animate-spin"/>Cargando reportes…</p>;if(!d)return null;const cards=[['Cumplimiento',`${(d.kpis.compliance*100).toFixed(1)}%`],['Esperadas',d.kpis.expected],['Registradas',d.kpis.registered],['Ausencias',d.kpis.absences],['Sin cobertura',d.kpis.uncovered],['Vacantes',d.kpis.vacancies],['Cumpleaños',d.kpis.birthdays],['Ingresos',d.kpis.entries],['Retiros',d.kpis.exits]];const maxNovelty=Math.max(1,...d.byNovelty.map(x=>x[1])),maxDaily=Math.max(1,...d.daily.map(x=>x.records));return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black">Dashboard operativo</h1><p className="text-sm text-slate-500">Última fecha transaccional: {d.latest}</p></div><button className="btn-secondary" disabled={exporting} onClick={exportXlsx}>{exporting?<Loader2 className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}Exportar XLSX</button></div>
<div className="card grid gap-3 p-4 md:grid-cols-4"><label className="label">Regional<select className="field mt-1" value={regional} onChange={e=>{setRegional(e.target.value);setGerencia('')}}><option value="">Todas</option>{regionales.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">Gerencia<select className="field mt-1" value={gerencia} onChange={e=>setGerencia(e.target.value)}><option value="">Todas</option>{gerencias.map(x=><option key={x}>{x}</option>)}</select></label><label className="label">Desde<input className="field mt-1" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="label">Hasta<input className="field mt-1" type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div>
<div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{cards.map(([label,value])=><div className="card border-l-4 border-l-blue-700 p-4" key={label}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>)}</div>
<section className="card p-5"><h2 className="flex items-center gap-2 font-black">Definiciones KPI <Info className="h-4 w-4"/></h2><dl className="mt-3 grid gap-3 text-sm md:grid-cols-2">{Object.entries(d.definitions).map(([k,v])=><div key={k}><dt className="font-bold capitalize">{k}</dt><dd className="text-slate-600">{v}</dd></div>)}</dl></section>
<div className="grid gap-4 lg:grid-cols-2"><section className="card p-5"><h2 className="font-black">Ausentismo por novedad</h2><div className="mt-4 space-y-3">{d.byNovelty.map(([name,count])=><div key={name}><div className="flex justify-between text-sm"><span>{name}</span><b>{count}</b></div><Bar value={count} max={maxNovelty} label={name} color="bg-red-500"/></div>)}</div></section><section className="card p-5"><h2 className="font-black">Tendencia diaria</h2><div className="mt-4 max-h-80 space-y-3 overflow-auto">{d.daily.map(x=><div key={x.date}><div className="flex justify-between text-sm"><span>{x.date}</span><b>{x.records} registros · {x.absences} ausencias</b></div><Bar value={x.records} max={maxDaily} label={x.date}/></div>)}</div></section></div>
<section className="card p-5"><h2 className="font-black">Cumplimiento por gerencia</h2><div className="mt-3 overflow-auto"><table className="min-w-full text-sm"><thead><tr><th className="p-2 text-left">Gerencia</th><th>Esperadas</th><th>Registradas</th><th>Cumplimiento</th></tr></thead><tbody>{d.byManagement.map(x=><tr className="border-t" key={x.name}><td className="p-2">{x.name}</td><td className="text-center">{x.expected}</td><td className="text-center">{x.registered}</td><td className="min-w-48 p-2"><span className="sr-only">{(x.compliance*100).toFixed(1)}%</span><Bar value={x.compliance} max={1} label={`${x.name} ${(x.compliance*100).toFixed(1)}%`} color={x.compliance>=.95?'bg-emerald-600':'bg-amber-500'}/></td></tr>)}</tbody></table></div></section>
<div className="grid gap-4 lg:grid-cols-3"><Detail title="Posiciones sin cobertura" rows={d.uncovered.map(x=>({regional:x.regional,gerencia:x.gerencia,nombre:x.sector,cedula:x.nombre}))}/><Detail title="Cumpleaños" rows={d.details.birthdays}/><Detail title="Ingresos y retiros" rows={[...d.details.entries.map(x=>({...x,date:x.fechaIngreso})),...d.details.exits]}/></div></div>}
function Detail({title,rows}:{title:string;rows:EventRow[]}){return <section className="card p-4"><h2 className="font-black">{title} · {rows.length}</h2><div className="mt-3 max-h-64 overflow-auto text-sm">{rows.length?rows.map((r,i)=><div className="border-t py-2" key={`${r.cedula}:${i}`}><b>{r.nombre||r.cedula}</b><p className="text-xs text-slate-500">{r.gerencia} {r.date?`· ${r.date}`:''}</p></div>):<p className="text-slate-500">Sin registros en el rango.</p>}</div></section>}
